In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# 概率模型

- 简单概率模型
- 马氏链模型
- 随机游走模型

##  马氏链模型

- 描述一类重要的随机动态系统（过程）的模型
- 从一时期到下时期所处的状态是随机的
- 下时期状态只取决于本时期状态和转移概率 **(已知现在，将来于过去无关（无后效性）**

### 1.健康与疾病
Eg1. 人的健康状况分为健康和疾病两种状态，设对特定年龄段的人，今年健康、明年保持健康状态的概率为0.8, 而今年患病、明年转为健康状态的概率为0.7.

我们可以定义一个矩阵模型，如下所示：

In [2]:
P = np.array([[0.8, 0.2],
              [0.7, 0.3]])

for _ in range(30):
    P = np.dot(P, P)

print(P)

[[0.77777782 0.22222223]
 [0.77777782 0.22222223]]


我们可以发现当$n\rightarrow\infty \, , P \rightarrow C$,并且稳定值与初始状态无关。

Eg2. 健康和疾病状态同上，$X_n=1$~ 健康, $X_n = 2$ ~ 疾病,死亡为第三种状态，记为$X_n = 3$，我们可以定义一个新的矩阵：

In [3]:
P = np.array([[0.8, 0.18, 0.02],
              [0.65, 0.25, 0.1],
              [0, 0, 1]])

for _ in range(30):
    P = np.dot(P, P)

print(P)

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


### 2. 钢琴销售的存储策略
钢琴销售量很小，商店的库存量不大以免积压资金. 一家商店根据经验估计，平均每周的钢琴需求为1架
存贮策略：每周末检查库存量，仅当库存量为零时，才订购3架供下周销售；否则，不订购

- 估计在这种策略下失去销售机会的可能性有多大?
- 以及每周的平均销售量是多少

动态过程中每周销售量不同，失去销售机会（需求超过库存）的概率不同.可按稳态情况（时间充分长以后）计算失去销售机会的概率和每周的平均销售量。

In [4]:
P = np.array([[0.368, 0, 0.632],
              [0.368, 0.368, 0.264],
              [0.184, 0.368, 0.448]])
for _ in range(30):
    P = np.dot(P, P)

print(P)

[[0.28483488 0.26318077 0.45198436]
 [0.28483488 0.26318077 0.45198436]
 [0.28483488 0.26318077 0.45198436]]


从上述分析中，可以得到稳态分布是$[0.2848, 0.2632, 0.4520]$,进而可以如下的计算出来失去销售的机会的概率以及每周的平均销售量:


In [5]:
pai = P[0]
D = np.array([0.368, 0.368, 0.184, 0.061, 0.019])
total_pro = 0
for k in range(1, 4):
    total_pro += np.sum(D[k + 1:]) * pai[k - 1]
    
print("失去销售机会的可能性为%.2f%%" %(total_pro * 100))

total_sell = 0
for k in range(1, 4):
    total_sell += np.sum(D[0:k + 1]) * pai[k - 1]

print("每周的平均销售量为 %.2f" %(total_sell))

失去销售机会的可能性为10.48%
每周的平均销售量为 0.90
